#! /bin/sh
ldconfig

# Assigning IP addr for P15-LG-eth0
ip link set dev P15-LG-eth0 up
ip -6 addr add fde4:5:1700::0010/127 dev P15-LG-eth0

# Assigning IP addr for P15-LG-eth1
ip link set dev P15-LG-eth1 up
ip -6 addr add fde4:5:1b00::00b0/127 dev P15-LG-eth1

# Assiging IP addr for loopback
ip -6 addr add fde4:5:2700::0001/128 dev lo
		 

# zebra is required to make the link between all FRRouting daemons
# and the linux kernel routing table
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/zebra -A 127.0.0.1 -f /etc/zebra.conf -z /tmp/p15-lg.api -i /tmp/p15-lg_zebra.pid --v6-rr-semantics &

# launching FRRouting OSPF daemon
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/ospf6d -f /etc/p15-lg_ospf.conf -z /tmp/p15-lg.api -i /tmp/p15-lg_ospf6d.pid -A 127.0.0.1 &

# launching FRRouting BGP daemon
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/bgpd -f /etc/p15-lg_bgp.conf -z /tmp/p15-lg.api -i /tmp/p15-lg_bgp.pid -A 127.0.0.1 &

# Setting up the firewall
/etc/p15-lg_firewall.sh

# Export vtysh
export LD_LIBRARY_PATH=/usr/local/lib
