#! /bin/sh
ldconfig

# Assigning IP addr for P2-BR-eth0
ip link set dev P2-BR-eth0 up
ip -6 addr add fde4:5:11::2/127 dev P2-BR-eth0

# Assigning IP addr for P2-BR-eth1
ip link set dev P2-BR-eth1 up
ip -6 addr add fde4:5:11::4/127 dev P2-BR-eth1

# Assigning IP addr for P2-BR-eth2
ip link set dev P2-BR-eth2 up
ip -6 addr add fde4:5:11::5/127 dev P2-BR-eth2

# Assigning IP addr for P2-BR-eth3
ip link set dev P2-BR-eth3 up
ip -6 addr add fde4:5:1b::5/127 dev P2-BR-eth3

# Assiging IP addr for loopback
ip -6 addr add fde4:5:21::2/128 dev lo
		 

# zebra is required to make the link between all FRRouting daemons
# and the linux kernel routing table
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/zebra -A 127.0.0.1 -f /etc/zebra.conf -z /tmp/p2-br.api -i /tmp/p2-br_zebra.pid &

# launching FRRouting OSPF daemon
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/ospf6d -f /etc/p2-br_ospf.conf -z /tmp/p2-br.api -i /tmp/p2-br_ospf6d.pid -A 127.0.0.1 &

# launching FRRouting BGP daemon
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/bgpd -f /etc/p2-br_bgp.conf -z /tmp/p2-br.api -i /tmp/p2-br_bgp.pid -A 127.0.0.1 &

# Export vtysh
export LD_LIBRARY_PATH=/usr/local/lib
