#! /bin/sh
ldconfig

# Assigning IP addr for P3-BR-eth0
ip link set dev P3-BR-eth0 up
ip -6 addr add fde4:5:1100::0020/127 dev P3-BR-eth0

# Assigning IP addr for P3-BR-eth1
ip link set dev P3-BR-eth1 up
ip -6 addr add fde4:5:1100::0040/127 dev P3-BR-eth1

# Assigning IP addr for P3-BR-eth2
ip link set dev P3-BR-eth2 up
ip -6 addr add fde4:5:1100::0060/127 dev P3-BR-eth2

# Assiging IP addr for loopback
ip -6 addr add fde4:5:2100::0003/128 dev lo
		 

# zebra is required to make the link between all FRRouting daemons
# and the linux kernel routing table
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/zebra -A 127.0.0.1 -f /etc/zebra.conf -z /tmp/p3-br.api -i /tmp/p3-br_zebra.pid --v6-rr-semantics &

# launching FRRouting OSPF daemon
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/ospf6d -f /etc/p3-br_ospf.conf -z /tmp/p3-br.api -i /tmp/p3-br_ospf6d.pid -A 127.0.0.1 &

# launching FRRouting BGP daemon
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/bgpd -f /etc/p3-br_bgp.conf -z /tmp/p3-br.api -i /tmp/p3-br_bgp.pid -A 127.0.0.1 &

# Setting up the firewall
/etc/p3-br_firewall.sh

# Export vtysh
export LD_LIBRARY_PATH=/usr/local/lib
