#! /bin/sh
ldconfig

# Assigning IP addr for P9-FB-eth0
ip link set dev P9-FB-eth0 up
ip -6 addr add fde4:5:1400::0010/127 dev P9-FB-eth0

# Assigning IP addr for P9-FB-eth1
ip link set dev P9-FB-eth1 up
ip -6 addr add fde4:5:1b00::0050/127 dev P9-FB-eth1

# Assigning IP addr for celadon
ip link set dev celadon up
ip -6 addr add fde4:4:f001:5::dead/64 dev celadon

# Assiging IP addr for loopback
ip -6 addr add fde4:5:2400::0001/128 dev lo
		 

# zebra is required to make the link between all FRRouting daemons
# and the linux kernel routing table
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/zebra -A 127.0.0.1 -f /etc/zebra.conf -z /tmp/p9-fb.api -i /tmp/p9-fb_zebra.pid --v6-rr-semantics &

# launching FRRouting OSPF daemon
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/ospf6d -f /etc/p9-fb_ospf.conf -z /tmp/p9-fb.api -i /tmp/p9-fb_ospf6d.pid -A 127.0.0.1 &

# launching FRRouting BGP daemon
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/bgpd -f /etc/p9-fb_bgp.conf -z /tmp/p9-fb.api -i /tmp/p9-fb_bgp.pid -A 127.0.0.1 &

# Setting up the firewall
/etc/p9-fb_firewall.sh

# Export vtysh
export LD_LIBRARY_PATH=/usr/local/lib
